### ISSUE TITLE
ModuleNotFoundError: No module named 'redis'

### ISSUE THREAD

**Issue by romanrsr** [wanghaisheng/tiktoka-studio-uploader#69]
### Checklist

- [X] I'm reporting a bug unrelated to a specific site
- [X] I've verified that I'm running ytb_up version **0.1.15** ([update instructions](https://github.com/wanghaisheng/tiktoka-studio-uploader/#update)) or later (specify commit)
- [X] I've checked that all provided URLs are playable in a browser with the same IP and same login details
- [X] I've checked that all URLs and arguments with special characters are [properly quoted or escaped](https://github.com/ytdl-org/youtube-dl#video-url-contains-an-ampersand-and-im-getting-some-strange-output-1-2839-or-v-is-not-recognized-as-an-internal-or-external-command)
- [X] I've searched the [bugtracker](https://github.com/wanghaisheng/tiktoka-studio-uploader/issues?q=) for similar issues including closed ones. DO NOT post duplicates
- [X] I've read the [guidelines for opening an issue](https://github.com/wanghaisheng/tiktoka-studio-uploader/blob/master/CONTRIBUTING.md#opening-an-issue)

### Description

I'm using Python version 3.10.0.
Redis 3.5.3 Installed

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\youtube\tiktoka-studio-uploader\examples\onefile-example_tiktok_sessionid.py", line 1, in <module>
    from tsup.tiktok.sessionId.uploader import  upload2TiktokSessionId
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\__init__.py", line 25, in <module>
    from tsup.youtube.youtube_upload import YoutubeUpload
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\youtube\youtube_upload.py", line 12, in <module>
    from tsup.utils.webdriver import (
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\utils\webdriver\__init__.py", line 10, in <module>
    from tsup.utils.webdriver.playwright_driver_async import PlaywrightAsyncDriver
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\utils\webdriver\playwright_driver_async.py", line 28, in <module>
    from tsup.utils import tools
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\tsup-0.1.16-py3.10.egg\tsup\utils\tools.py", line 44, in <module>
    import redis
ModuleNotFoundError: No module named 'redis'

**Comment by wanghaisheng** [comment]
can you try 
git checkout -b publish_policy
and run pip install -r requirements.txt
then your command
